atch(int i)  {
//  cout<<"caught exception "<<i<<endl;
//  }